from odoo import fields, models


class StockPackageType(models.Model):
    _inherit = "stock.package.type"

    package_carrier_type = fields.Selection(
        selection_add=[
            ("a2b", "A2B"),
            ("asendia", "Asendia"),
            ("bring", "Bring"),
            ("budbee", "Budbee"),
            ("dhl_freight", "DHL Freight"),
            ("dpd", "DPD"),
            ("dsv", "DSV"),
            ("fetch", "Fetch"),
            ("gls", "GLS"),
            ("instabox", "Instabox"),
            ("itella_logistiikka", "Itella Logistiikka"),
            ("jakeluyhtio_suomi", "Jakeluyhtiö Suomi"),
            ("kaukokiito", "Kaukokiito"),
            ("db_schenker_system", "DB Schenker System"),
            ("matkahuolto", "Matkahuolto"),
            ("postnord", "Postnord"),
            ("posti", "Posti"),
            ("db_schenker_suomi", "DB Schenker Finland"),
            ("smartposti", "SmartPosti"),
            ("unisend", "Unisend"),
            ("ups", "UPS"),
            ("venipak", "Venipak"),
            ("wolt", "Wolt"),
        ],
        ondelete={
            "a2b": "set default",
            "asendia": "set default",
            "bring": "set default",
            "budbee": "set default",
            "dhl_freight": "set default",
            "dpd": "set default",
            "dsv": "set default",
            "fetch": "set default",
            "gls": "set default",
            "instabox": "set default",
            "itella_logistiikka": "set default",
            "jakeluyhtio_suomi": "set default",
            "kaukokiito": "set default",
            "db_schenker_system": "set default",
            "matkahuolto": "set default",
            "postnord": "set default",
            "posti": "set default",
            "db_schenker_suomi": "set default",
            "smartposti": "set default",
            "unisend": "set default",
            "ups": "set default",
            "venipak": "set default",
            "wolt": "set default",
        },
    )
